# Generated by Django 5.2.8 on 2025-11-24 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_patient_age_alter_patient_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_doctor': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_patient': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
